dashboard_base_card:
  type: custom:button-card
  template:
    - base_card
  styles:
    card:
      - background: var(--ha-card-background)

base_card:
  type: custom:button-card
  tap_action:
    action: toggle
  hold_action:
    action: more-info
  show_label: false
  show_state: true
  styles:
    card:
      - padding: 16px
      - background: var(--popupBG)
    grid:
      - grid-template-areas: '"i n" "i s"'
      - grid-template-columns: min-content 1fr
      - grid-column-gap: 16px
    img_cell:
      - justify-self: start
      - width: 24px
    icon:
      - width: 24px
      - color: var(--highlight)
    name:
      - justify-self: start
      - font-size: 14px
      - color: var(--highlight)
      - opacity: 0.8
    state:
      - justify-self: start
      - font-size: 16px
      - font-weight: 500
      - padding-top: 2px
      - color: var(--highlight)

state_gradient:
  type: custom:button-card
  state:
    - value: "on"
      styles:
        card:
          - background: var(--active-light)
        icon:
          - color: var(--black)
        name:
          - color: var(--black)
        state:
          - color: var(--black)
